site_name: Hướng dẫn KidSafe
site_url: https://kidsafe.com.vn/
site_description: Hướng dẫn cài đặt và sử dụng KidSafe.
site_author: GreenKite Co.
theme:
    name: material
    color_mode: auto
    user_color_mode_toggle: true
    locale: en
    analytics:
        gtag: G-274394082
    highlightjs: true
    hljs_languages:
        - yaml
        - django

markdown_extensions:
    - toc:
          permalink: true
    - attr_list
    - def_list
    - tables
    - pymdownx.highlight:
          use_pygments: false
    - pymdownx.snippets
    - pymdownx.superfences
    - callouts
    - mdx_gh_links:
          user: mkdocs
          repo: mkdocs
    - mkdocs-click

copyright: Copyright &copy; 2024 <a href="https://twitter.com/starletdreaming">GreenKite Co.</a>

hooks:
    - docs/hooks.py

plugins:
    - search
    #     - redirects:
    #           redirect_maps:
    #               user-guide/plugins.md: dev-guide/plugins.md
    #               user-guide/custom-themes.md: dev-guide/themes.md
    #               user-guide/styling-your-docs.md: user-guide/choosing-your-theme.md
    - autorefs
    - literate-nav:
          nav_file: README.md
          implicit_index: true
    - mkdocstrings:
          handlers:
              python:
                  options:
                      docstring_section_style: list
                      members_order: source
                      show_root_heading: true
                      show_source: false
                      show_signature_annotations: true

watch:
    - docs

extra_css:
    - css/extra.css
    - css/general.css
    - css/queries.css
    - css/style.css

exclude_docs: |
    *.py
nav:
    - Home: index.md
    - 1. Hướng dẫn cài đặt: install-guide/
    - 2. Hướng dẫn sử dụng: usage-guide/
    - Help:
          - Hỏi đáp: help/qa.md
          - Mở KidSafe: help/open-pc.md
          - Gỡ cài đặt KidSafe: help/uninstall-pc.md
    - Other: tip/
